### ISSUE TITLE
WebView2Wpf init

### ISSUE THREAD

**Issue by jiongge** [ChrisPulman/CrissCross#86]
Thanks because this project solved my problem!
But the question is I want to know when the WebView2 initialization is done
Can set _WebBrowser into public or implement EnsureCoreWebView2Async method and CoreWebView2InitializationCompleted event

Thanks！~~

[https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=webview2-dotnet-1.0.2365.46](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=webview2-dotnet-1.0.2365.46)

**Comment by jiongge** [comment]
![image](https://github.com/ChrisPulman/CrissCross/assets/1711945/1cd9ca3a-e553-43aa-9dc2-46fd2a288caa)

**Comment by jiongge** [comment]
Unloaded += (s, e) => Dispose(); I don't think that's necessary
Switching pages after I put WebView2Wpf into the Page caused problems

**Comment by ChrisPulman** [comment]
> Unloaded += (s, e) => Dispose(); I don't think that's necessary Switching pages after I put WebView2Wpf into the Page caused problems

This is to release the Web View and allow exit of the App, I will add a property to allow you to change this as a setting, `AutoDispose` it is defaulted to true so as not to break existing functionality.

**Comment by ChrisPulman** [comment]
@jiongge Please check the latest version, hopefully it contains all you need as per your request. You may need to set the `AutoDispose` property to `false` to fit your needs. You will then need to Dispose the control to release resources allowing your App to shutdown, toggling this property True to False will remove the Dispose handler on Unloaded, toggling this property False to True will add the Dispose handler on Unloaded.
If there is anything missing, please let me know and I will do my best to add any additions.

**Comment by jiongge** [comment]
it's perfect for me. Thank you!~~

**Comment by jiongge** [comment]
it's perfect for me. Thank you!~~
